version: '3.8'

services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    shm_size: "1gb"
    restart: unless-stopped
