export const API_ROUTES = {
  auth: {
    me: '/api/v1/auth/me',
    google: '/api/v1/auth/google',
    sendOtp: '/api/v1/auth/send-otp',
    verifyOtp: '/api/v1/auth/verify-otp',
  },
  onboarding: {
    upsert: '/api/v1/onboarding',
  },
  agent: {
    session: '/api/v1/agent/session',
    sessionById: (sid: string, view?: 'summary' | 'status' | 'context_pool' | 'website_snapshot') =>
      `/api/v1/agent/session/${encodeURIComponent(sid)}${view ? `?view=${encodeURIComponent(view)}` : ''}`,
    patchSession: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}`,
    advanceSession: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/advance`,
    sessionStatus: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/status`,
    websiteSnapshot: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/website-snapshot`,
    contextPool: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/context-pool`,
    outcome: '/api/v1/agent/session/outcome',
    domain: '/api/v1/agent/session/domain',
    task: '/api/v1/agent/session/task',
    url: '/api/v1/agent/session/url',
    skipUrl: '/api/v1/agent/session/skip-url',
    crawlStatus: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/crawl-status`,
    scaleQuestions: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/scale-questions`,
    scaleAnswers: '/api/v1/agent/session/scale-answers',
    startDiagnostic: '/api/v1/agent/session/start-diagnostic',
    answer: '/api/v1/agent/session/answer',
    precisionQuestions: '/api/v1/agent/session/precision-questions',
    recommend: '/api/v1/agent/session/recommend',
  },
  playbook: {
    start: '/api/v1/playbook/start',
    generate: '/api/v1/playbook/generate',
    generateStream: '/api/v1/playbook/generate-stream',
    gapAnswers: '/api/v1/playbook/gap-answers',
  },
  payments: {
    createOrder: '/api/v1/payments/create-order',
    status: (orderId: string) => `/api/v1/payments/status/${encodeURIComponent(orderId)}`,
  },
  legacy: {
    saveIdea: '/api/save-idea',
    chat: '/api/chat',
    searchCompanies: '/api/search-companies',
    marketIntelligence: '/api/market-intelligence',
  },
  aiChat: {
    stream: '/api/v1/ai-chat/stream',
    message: '/api/v1/ai-chat/message',
    messageBackground: '/api/v1/ai-chat/message/background',
    messages: '/api/v1/ai-chat/messages',
    conversations: '/api/v1/ai-chat/conversations',
    conversationById: (id: string) => `/api/v1/ai-chat/conversations/${encodeURIComponent(id)}`,
    skills: '/api/v1/ai-chat/skills',
    skillCalls: '/api/v1/ai-chat/skill-calls',
    tokenUsage: '/api/v1/ai-chat/token-usage',
    planStatus: '/api/v1/ai-chat/plan-status',
  },
  agents: {
    base: '/api/agents',
    byId: (id: string) => `/api/agents/${encodeURIComponent(id)}`,
  },
} as const;

