export const API_ROUTES = {
  auth: {
    me: '/api/v1/auth/me',
    google: '/api/v1/auth/google',
    sendOtp: '/api/v1/auth/send-otp',
    verifyOtp: '/api/v1/auth/verify-otp',
  },
  agent: {
    session: '/api/v1/agent/session',
    outcome: '/api/v1/agent/session/outcome',
    domain: '/api/v1/agent/session/domain',
    task: '/api/v1/agent/session/task',
    answer: '/api/v1/agent/session/answer',
    precisionQuestions: '/api/v1/agent/session/precision-questions',
    website: '/api/v1/agent/session/website',
    scaleAnswers: '/api/v1/agent/session/scale-answers',
    startDiagnostic: '/api/v1/agent/session/start-diagnostic',
    url: '/api/v1/agent/session/url',
    skipUrl: '/api/v1/agent/session/skip-url',
    recommend: '/api/v1/agent/session/recommend',
    websiteSnapshot: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/website-snapshot`,
    crawlStatus: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/crawl-status`,
    scaleQuestions: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/scale-questions`,
    contextPool: (sid: string) => `/api/v1/agent/session/${encodeURIComponent(sid)}/context-pool`,
  },
  playbook: {
    start: '/api/v1/playbook/start',
    generate: '/api/v1/playbook/generate',
    gapAnswers: '/api/v1/playbook/gap-answers',
  },
  payments: {
    createOrder: '/api/v1/payments/create-order',
    status: (orderId: string) => `/api/v1/payments/status/${encodeURIComponent(orderId)}`,
  },
  legacy: {
    saveIdea: '/api/save-idea',
    chat: '/api/chat',
    searchCompanies: '/api/search-companies',
    marketIntelligence: '/api/market-intelligence',
  },
  aiChat: {
    plan: '/api/chat/plan',
    planStream: '/api/chat/plan/stream',
    planApproveStream: '/api/chat/plan/approve/stream',
    stream: '/api/chat/stream',
    message: '/api/chat/message',
    messages: '/api/chat/messages',
    conversations: '/api/chat/conversations',
    conversationById: (id: string) => `/api/chat/conversations/${encodeURIComponent(id)}`,
    skills: '/api/chat/skills',
    skillCalls: '/api/chat/skill-calls',
    tokenUsage: '/api/chat/token-usage',
  },
  agents: {
    base: '/api/agents',
    byId: (id: string) => `/api/agents/${encodeURIComponent(id)}`,
  },
  sandbox: {
    login: '/api/v1/sandbox/login',
    testSession: '/api/v1/sandbox/test/session',
    testOutcome: '/api/v1/sandbox/test/outcome',
    testDomain: '/api/v1/sandbox/test/domain',
    testTask: '/api/v1/sandbox/test/task',
    testAnswer: '/api/v1/sandbox/test/answer',
    testRecommend: '/api/v1/sandbox/test/recommend',
    logs: '/api/v1/sandbox/logs',
    logsBySession: (sid: string) => `/api/v1/sandbox/logs/${encodeURIComponent(sid)}`,
    exportSession: (sid: string) => `/api/v1/sandbox/logs/export/${encodeURIComponent(sid)}`,
    exportGlobal: '/api/v1/sandbox/logs/export-all/global',
  },
} as const;

