// ─── Q1: Outcome Options ───────────────────────────────────────────
export const outcomeOptions = [
  { id: 'lead-generation', text: 'Lead Generation', subtext: 'Marketing, SEO & Social' },
  { id: 'sales-retention', text: 'Sales & Retention', subtext: 'Calling, Support & Expansion' },
  { id: 'business-strategy', text: 'Business Strategy', subtext: 'Intelligence, Market & Org' },
  { id: 'save-time', text: 'Save Time', subtext: 'Automation Workflow, Extract PDF, Bulk Task' },
];

// ─── Q2: Domains per Outcome ──────────────────────────────────────
export const OUTCOME_DOMAINS = {
  'lead-generation': [
    'Content & Social Media',
    'SEO & Organic Visibility',
    'Paid Media & Ads',
    'B2B Lead Generation',
  ],
  'sales-retention': [
    'Sales Execution & Enablement',
    'Lead Management & Conversion',
    'Customer Success & Reputation',
    'Repeat Sales',
  ],
  'business-strategy': [
    'Business Intelligence & Analytics',
    'Market Strategy & Innovation',
    'Financial Health & Risk',
    'Org Efficiency & Hiring',
    'Improve Yourself',
  ],
  'save-time': [
    'Sales & Content Automation',
    'Finance Legal & Admin',
    'Customer Support Ops',
    'Recruiting & HR Ops',
    'Personal & Team Productivity',
  ],
};

// ─── Q3: Tasks per Domain ─────────────────────────────────────────
export const DOMAIN_TASKS = {
  'Content & Social Media': [
    'Generate social media posts captions & hooks',
    'Create AI product photography & video ads',
    'Build a personal brand on LinkedIn/Twitter',
    'Repurpose content for maximum reach',
    'Spot trending topics & viral content ideas',
  ],
  'SEO & Organic Visibility': [
    'Get more leads from Google & website (SEO)',
    'Google Business Profile visibility',
    'Improve Google Business Profile leads',
    'Write SEO Keyword blogs and landing pages',
    'Write product titles that rank SEO',
    'Ecommerce Listing SEO + upsell bundles',
  ],
  'Paid Media & Ads': [
    'Generate high-converting ad copy & visuals',
    'Auto-optimize campaigns to boost ROAS',
    'Find winning audiences & keywords',
    'Audit ad spend & spot wasted budget',
    'Spy on competitor ads & offers',
  ],
  'B2B Lead Generation': [
    'Find decision-maker emails & LinkedIn profiles',
    'Generate hyper-personalized cold outreach sequences',
    'Identify target companies by tech stack & intent',
    'Score & prioritize leads by ICP match',
    'Automate LinkedIn connection & engagement',
  ],
  'Sales Execution & Enablement': [
    'Selling on WhatsApp/Instagram',
    'Speed up deal closure with faster contract review',
    'Chat with past campaigns and assets',
  ],
  'Lead Management & Conversion': [
    'Qualify & route leads automatically (AI SDR)',
    'Lead Qualification Follow Up & Conversion',
    'Reduce missed leads with faster replies',
    'Find why customers don\'t convert',
    'Understanding why customers don\'t convert',
  ],
  'Customer Success & Reputation': [
    'Improve reviews and response quality',
    'Call Chat & Ticket Intelligence',
    'Improve retention and reduce churn',
    'Churn & retention insights',
    'Support SLA dashboard',
    'Call/chat/ticket intelligence insights',
    'Review sentiment + issue detection',
  ],
  'Repeat Sales': [
    'Upsell/cross-sell recommendations',
    'Create upsell/cross-sell messaging',
    'Improve order experience to boost repeats',
  ],
  'Business Intelligence & Analytics': [
    'Instant sales dashboard (daily/weekly)',
    'Marketing performance dashboard (ROI)',
    'Campaign performance tracking dashboard',
    'Track calls Clicks and form fills',
    'Call/chat/ticket insights from conversations',
    'Review sentiment → improvement ideas',
    'Review sentiment + competitor comparisons',
    'Ops dashboard (orders blacklog SLA)',
  ],
  'Market Strategy & Innovation': [
    'Business Idea Generation',
    'Trending Products',
    'Track competitors pricing and offers',
    'Market & industry trend summaries',
    'Predict demand & business outcomes',
    'Competitor monitoring & price alerts',
    'Market & trend research summaries',
    'AI research summaries for decisions',
    'Sales & revenue forecasting',
    'Predict demand and stock needs',
  ],
  'Financial Health & Risk': [
    'Spot profit leaks and improve margins',
    'Prevent revenue leakage from contracts',
    'Cashflow + spend control dashboard',
    'Instant finance dashboard (monthly/weekly)',
    'Budget vs actual insights with variance alerts',
    'Cashflow forecast (30/60/90 days)',
    'Spend control alerts and trend insights',
    'Contract risk snapshot',
    'Supplier risk and exposure tracking',
    'Supplier risk monitoring',
  ],
  'Org Efficiency & Hiring': [
    'Hire faster to support growth',
    'Build a knowledge base from SOPs',
    'Internal Q&A bot from SOPs/policies',
    'Industry best practice',
    'Delivery/logistics performance reporting',
    'Hiring funnel dashboard',
    'Improve hire quality insights',
    'Interview feedback summaries',
    'HR knowledge base from policies',
    'Internal Q&A bot for HR queries',
    'Organize resumes and candidate notes',
    'Brand monitoring & crisis alerts',
    'Search/chat across help docs',
    'Internal Q&A bot from SOPs',
    'Weekly goals + progress summary',
    'Chat with your personal documents',
    'Auto-tag and organize your files',
  ],
  'Improve Yourself': [
    'Plan weekly priorities and tasks',
    'Prep for pitches and presentations',
    'Personal branding content plan',
    'Create a learning plan + summaries',
    'Contract drafting & review support',
    'Team Spirit Action plan',
  ],
  'Sales & Content Automation': [
    'Automate lead capture into Sheets/CRM',
    'Auto-capture leads from forms/ads',
    'Draft proposals quotes and emails faster',
    'Mail + DM + influencer outreach automation',
    'Auto-reply + follow-up sequences',
    'Summarize calls/chats into CRM notes',
    'Repurpose long videos into shorts',
    'Schedule posts + reuse content ideas',
    'Bulk update product listings/catalog',
    'Generate A+ store content at scale',
    'Auto-create weekly content calendar',
  ],
  'Finance Legal & Admin': [
    'Automate procurement requests/approvals',
    'Automate procurement approvals',
    'Automate HR or Finance',
    'Extract invoice/order data from PDFs',
    'Extract invoices/receipts from PDFs into Sheets',
    'Classify docs (invoice/contract/report)',
    'Bookkeeping assistance + auto categorization',
    'Expense tracking + spend control automation',
    'Auto-generate client/vendor payment reminders',
    'Draft finance emails reports and summaries faster',
    'Extract key terms from contracts',
    'Automate contract approvals renewals and deadline reminders',
    'Compliance checklist summaries and policy Q&A',
  ],
  'Customer Support Ops': [
    '24/7 support assistant + escalation',
    'Automate order updates and tracking',
    'Track orders + customer notifications',
    'Support ticket routing automation',
    'Auto-tag route and prioritize tickets',
    'Draft replies in brand voice',
    'WhatsApp/Instagram instant replies',
    'Build a support knowledge base',
  ],
  'Recruiting & HR Ops': [
    'Find candidates faster (multi-source)',
    'Resume screening + shortlisting',
    'Automate interview scheduling',
    'Automate candidate follow-ups',
    'High-volume hiring coordination',
    'Onboarding checklists + HR support',
    'Draft job descriptions and outreach',
  ],
  'Personal & Team Productivity': [
    'Summarize meetings + action items',
    'Summarize meetings + send action items',
    'Extract data from PDFs/images to Sheets',
    'Extract data from PDFs/images',
    'Automate repetitive admin workflows',
    'Excel and App script Automation',
    'Auto-tag and organize documents',
    'Organize notes automatically',
    'Draft emails reports and proposals',
    'Summarize PDFs and long documents',
  ],
};
